- id: node1
  host: 127.0.0.1
  port: 8081
  useGrpc: true

- id: node2
  host: 127.0.0.1
  port: 8082
  useGrpc: true

#- id: node3
#  host: 192.168.1.100
#  port: 8083
#  useGrpc: true
#
#- id: node4
#  host: 192.168.1.101
#  port: 8084
#  useGrpc: false